### ISSUE TITLE
TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/discovery-swarm#15]
```
/Users/paulfrazee/pubpeer/hypercloud/node_modules/discovery-swarm/index.js:127
    if (opts.announce) port = this.address().port
                                            ^

TypeError: Cannot read property 'port' of null
    at Swarm.join (/Users/paulfrazee/pubpeer/hypercloud/node_modules/discovery-swarm/index.js:127:45)
    at serveArchive (/Users/paulfrazee/pubpeer/hypercloud/node_modules/archiver-server/index.js:103:11)
    at Timeout._onTimeout (/Users/paulfrazee/pubpeer/hypercloud/node_modules/archiver-server/index.js:91:7)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```

**Comment by wellsmt** [comment]
I ran into this same issue when trying to call close(), were you able to resolve this @pfrazee ?
