### ISSUE TITLE
Error when {tcp: false, utp: true}

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/discovery-swarm#7]
Maybe `this.address()` instead of `this._tcp.address()`?

```
/Users/paul/projects/exandria/node_modules/discovery-swarm/index.js:120
    this._discovery.join(name, this._tcp.address().port, {impliedPort: !!this._utp})
                                        ^

TypeError: Cannot read property 'address' of null
    at Swarm.join (/Users/paul/projects/exandria/node_modules/discovery-swarm/index.js:120:41)
    at Swarm._ondiscover (/Users/paul/projects/exandria/node_modules/discovery-swarm/index.js:182:47)
    at emitNone (events.js:91:20)
    at Swarm.emit (events.js:185:7)
    at UTP.onlisten (/Users/paul/projects/exandria/node_modules/discovery-swarm/index.js:395:10)
    at emitNone (events.js:86:13)
    at UTP.emit (events.js:185:7)
    at /Users/paul/projects/exandria/node_modules/utp-native/index.js:415:15
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mafintosh** [comment]
nice catch, fixed in 4.0.2
